[tool.pyright]
typeCheckingMode = "basic"
reportGeneralTypeIssues = "warning"

[tool.pylance]
python.analysis.typeCheckingMode = "basic"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = false

[tool.django-stubs]
django_settings_module = "config.settings"
