# Generated by Django 4.2.17 on 2024-12-13 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questioncategory_user_birth_date_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'order', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Question Categories'},
        ),
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'ordering': ['question', 'order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='max_age_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='min_age_preference',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='scale_value',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='accounts.questionchoice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('scale', 'Scale')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together={('question', 'value')},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('looking_for', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=20)),
                ('min_age_preference', models.IntegerField(blank=True, null=True)),
                ('max_age_preference', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
