# Generated by Django 5.0 on 2024-12-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matching_score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
